global:
  scrape_interval: 5s

scrape_configs:
  - job_name: order-saga
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - order-service:8081
          - payment-service:8082
          - inventory-service:8083
          - shipping-service:8084
          - order-view-service:8086
