server:
  port: 8082
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/payments_db
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
        specific.avro.reader: true
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
    properties:
      schema.registry.url: http://localhost:8085
